--CREATING DATABASE--
CREATE DATABASE crudnodejsmysql;

-- USING THE DATABASE--

USE crudnodejsmysql;

--CREATING A TABLE--
CREATE TABLE customer(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL
);

-- TP SHOW ALL TABLES --
SHOW TABLES;

-- TO DESCRIBE THE TABLE --
DESCRIBE customer;